import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import useFetch from "@/libs/use-fetch";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ex.发请求

  const { data } = useFetch({
    url: 'http://127.0.0.1:4523/m1/4275099-0-default/pet/4',
    method: 'POST',
    params: { b: '1' }
  })
  return (
    <>
      <Head>
        <title>Nature Edge Sustainable Community</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/complogo.svg" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Professional team!!!!!!!!!</h1>
      </main>
    </>
  );
}
