'use client';
import React from 'react';
// import type { Metadata } from 'next';
import '@/styles/global.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ThemeProvider } from '@/components/ThemeProvider/themeProvider';
import DynamicBackground from '@/components/DynamicBackground';
import './globals.css';

import FloatSwitch from '@/components/FloatButton';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <title>Green Life community</title>
        <link rel='icon' href='/complogo.svg' />
      </head>
      <body style={{ margin: '0px', padding: '0px' }}>
        <ThemeProvider>
          <DynamicBackground>
            <AntdRegistry>
              <FloatSwitch />
              {children}
            </AntdRegistry>
          </DynamicBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
