'use client';
import Head from 'next/head';
import React from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/global.module.css';
import { Button } from 'antd';
import { useThemeContext } from '@/components/ThemeProvider/themeContext';
// import TopBar from '@/components/Topbar';
// import useFetch from '@/libs/use-fetch';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // ex.发请求

  // const { data } = useFetch({
  //   url: 'http://127.0.0.1:4523/m1/4275099-0-default/pet/4',
  //   method: 'POST',
  //   params: { b: '1' }
  // });

  // 使用时，使用useThemeContext更改主题
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { theme, toggleTheme } = useThemeContext();

  return (
    <>
      <Head>
        <title>Nature Edge Sustainable Community</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/complogo.svg' /> */}
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* <TopBar></TopBar> */}
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <h1 className={styles.classss}>Professional team!!!!!!!!!</h1>
          <div style={{ display: 'flex', justifyContent: 'space-around' }}>
            <Button type='primary' href='/tourist'>
              Tourist
            </Button>
            <Button type='primary' href='/proprietor' danger>
              Proprietor
            </Button>
            <Button onClick={() => toggleTheme && toggleTheme()}>QTQTQT</Button>
          </div>
        </div>
      </main>
    </>
  );
}
