'use client';
import Head from 'next/head';
import React, { useEffect } from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/global.module.css';
import { useThemeContext } from '@/components/ThemeProvider/themeContext';
import { UserType } from '@/types/data-types';
import { useStore } from '@/hooks/useStore';
import { useRouter } from 'next/navigation';

// import TopBar from '@/components/Topbar';
// import useFetch from '@/libs/use-fetch';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // 使用时，使用useThemeContext更改主题
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { theme, toggleTheme } = useThemeContext();
  const router = useRouter();

  const setStoreUserType = useStore(state => state.setUserType);
  const userType = useStore(state => state.userType);
  useEffect(() => {
    setStoreUserType(
      (localStorage.getItem('user-type') as UserType) || 'TOURIST'
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    console.log(userType);
    // 没有登录的话
    if (userType === ('' as UserType) || userType === 'TOURIST') {
      router.push('/tourist/main');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Nature Edge Sustainable Community</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/complogo.svg' /> */}
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* <TopBar></TopBar> */}
        {/* <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center'
          }}
        >
          <h1 className={styles.classss}>Different account types for test: </h1>
          <Image src={'/complogo.svg'} width={'70%'} height={'40vh'} alt='' />
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-around',
              width: '80%'
            }}
          >
            <Button
              type='primary'
              href='/tourist/main'
              onClick={() => {
                localStorage.setItem('user-type', 'TOURIST');
              }}
            >
              Anonymous
            </Button>
            <Button
              type='primary'
              href='/normal/main'
              onClick={() => {
                localStorage.setItem('user-type', 'NORMAL');
              }}
            >
              Normal
            </Button>
            <Button
              type='primary'
              href='/admin/main'
              onClick={() => {
                localStorage.setItem('user-type', 'ADMIN');
              }}
            >
              Admin
            </Button>
            <Button
              type='primary'
              href='/enterprise/main'
              onClick={() => {
                localStorage.setItem('user-type', 'ENTERPRISE');
              }}
            >
              Enterprise
            </Button>
            <Button type='primary' href='/login'>
              Login
            </Button>
          </div>
        </div> */}
      </main>
    </>
  );
}
